<a href="https://colab.research.google.com/github/VasavSrivastava/MAT422/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1.2.1 Linear Spaces**

#####**1.2.1.1 Linear Combinations**
#####A linear combination of vectors is the sum of scalars times the vectors. Below is a visual representation of a Linear Combination

In [1]:
# Import necessary library
import numpy as np

# Define the vectors
v1 = np.array([2, 3])
v2 = np.array([1, 4])

# Define the coefficients for the linear combination
alpha = 3
beta = -1

# Compute the linear combination
linear_combination = alpha * v1 + beta * v2

# Print out the vectors and their linear combination
print("Vector v1:", v1)
print("Vector v2:", v2)
print("Coefficients: alpha =", alpha, ", beta =", beta)
print("Linear Combination ({} * v1 + {} * v2):".format(alpha, beta), linear_combination)


Vector v1: [2 3]
Vector v2: [1 4]
Coefficients: alpha = 3 , beta = -1
Linear Combination (3 * v1 + -1 * v2): [5 5]


#####**1.2.1.2 Linear independece and dimension**
A Linear subspace is a subset of all linear combinations. A list of vectors are linearly independent if they cannot be written as a linear combination of others. In other words, Their sum of linear combination has to be zero.

In [2]:
import numpy as np

# Define the vectors
v1 = np.array([1, 2])
v2 = np.array([3, 4])
v3 = np.array([5, 6])

# Stack the vectors as columns of a matrix
matrix = np.column_stack([v1, v2, v3])

# Compute the rank of the matrix
rank = np.linalg.matrix_rank(matrix)

# Determine the number of vectors
num_vectors = matrix.shape[1]

# Check if the vectors are linearly independent
if rank == num_vectors:
    print("The vectors are linearly independent.")
else:
    print("The vectors are linearly dependent.")

# Output the matrix and its rank for reference
print("Matrix formed by stacking the vectors as columns:")
print(matrix)
print("Rank of the matrix:", rank)

The vectors are linearly dependent.
Matrix formed by stacking the vectors as columns:
[[1 3 5]
 [2 4 6]]
Rank of the matrix: 2


#**1.2.2 Orthogonality**

#####**1.2.2.1 Orthonormal Bases**

#####A list of vectors are orthogonal if their dot product is equal to zero. $<u_i, u_j> = 0$ where $i \neq j$.



In [2]:
import numpy as np

# Define three vectors in R^3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])

# Form a matrix with the vectors as columns
V = np.column_stack((v1, v2, v3))

# Check if the vectors are orthogonal by computing the dot products
dot_product_matrix = np.dot(V.T, V)

print("Dot product matrix:")
print(dot_product_matrix)

# Check if the matrix is diagonal
is_orthogonal_basis = np.allclose(dot_product_matrix, np.diag(np.diagonal(dot_product_matrix)))

if is_orthogonal_basis:
    print("The vectors form an orthogonal basis.")
else:
    print("The vectors do not form an orthogonal basis.")

#####**1.2.2.2 Best approximation theorem**
#####According to Best approximation theorem, for any given vector v, there is a unique vector w in subspace W that is closest to v. Therefore, w minimizes the distance between v and all other vectors in W.

In [ ]:
import numpy as np

# Define the vector v and the subspace W spanned by w
v = np.array([3, 4])
w = np.array([1, 2])

# Compute the orthogonal projection of v onto w
w_normalized = w / np.linalg.norm(w)  # Normalize the vector w
projection_length = np.dot(v, w_normalized)  # Length of the projection of v onto w_normalized
projection = projection_length * w_normalized  # The actual projection vector

# Output the result
print(f"Original vector v: {v}")
print(f"Spanning vector w: {w}")
print(f"Projection of v onto W (Best Approximation): {projection}")
print(f"Distance between v and its projection: {np.linalg.norm(v - projection)}")

#**1.2.3 Gram-Schmidt Process**

#####A set of linearly independent vectors can be transformed into an orthogonal (or orthonormal) set of vectors that span the same subspace using the Gram-Schmidt process. To ensure orthogonality, a vector is first modified by removing its projection onto the previously computed orthogonal vectors. An orthonormal set can be produced by normalising the resulting orthogonal vectors, if necessary.



In [3]:
import numpy as np

def gram_schmidt(V):
    """Applies the Gram-Schmidt process to a set of vectors V."""
    # Number of vectors
    n = V.shape[1]

    # Initialize an empty list to hold the orthogonal vectors
    U = np.zeros_like(V)

    for i in range(n):
        # Start with the original vector
        u = V[:, i]

        for j in range(i):
            # Subtract the projection of the vector onto each of the previous orthogonal vectors
            u -= np.dot(U[:, j], V[:, i]) / np.dot(U[:, j], U[:, j]) * U[:, j]

        # Add the orthogonalized vector to the list
        U[:, i] = u

    return U

# Example usage
V = np.array([[3.0, 1.0], [2.0, 2.0]])  # Original set of vectors
U = gram_schmidt(V)  # Apply Gram-Schmidt process

# Output the orthogonalized vectors
print("Original vectors:")
print(V)
print("\nOrthogonalized vectors:")
print(U)

Original vectors:
[[ 3.         -0.61538462]
 [ 2.          0.92307692]]

Orthogonalized vectors:
[[ 3.         -0.61538462]
 [ 2.          0.92307692]]


#**1.2.4 Eigenvalues and Eigenvectors**

#####An eigenvector is a non-zero vector that points in a direction that is invariant by the transformation and only varies by a scalar factor when the matrix is applied to it. The amount by which the eigenvector is scaled is indicated by the associated scalar, known as the eigenvalue. If $A$ is a matrix and $v$ is an eigenvector, then $Av=λv = Cv$, where $C$ is the eigenvalue.

In [4]:
import numpy as np

# Define a square matrix A
A = np.array([[4, 2],
              [1, 3]])

# Compute the eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Output the results
print("Matrix A:")
print(A)
print("\nEigenvalues:")
print(eigenvalues)
print("\nEigenvectors:")
print(eigenvectors)

Matrix A:
[[4 2]
 [1 3]]

Eigenvalues:
[5. 2.]

Eigenvectors:
[[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
