<a href="https://colab.research.google.com/github/VasavSrivastava/MAT422/blob/main/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**1.3.1 QR Decomposition**

#####QR decomposition is a matrix factorization technique where a matrix A is decomposed into the product of two matrices: $Q$ and $R$. Specifically, for a $m$ x $n$ matrix $A$, QR decomposition expresses $A$ as: $$A = QR$$

#####Where $Q$ is an orthogonal matrix, meaning that its columns are orthonormal vectors and $R$ is an upper triangular matrix, i.e every element below the diagonal are zero.







In [1]:
import numpy as np

# Define a square matrix A
A = np.array([[2, -2, 18],
              [2, 1, 0],
              [1, 2, 0]])

# Perform QR decomposition
Q, R = np.linalg.qr(A)

# Output the results
print("Matrix A:")
print(A)
print("\nMatrix Q (Orthogonal Matrix):")
print(Q)
print("\nMatrix R (Upper Triangular Matrix):")
print(R)

# Verify the decomposition (A should be equal to Q @ R)
A_reconstructed = np.dot(Q, R)
print("\nReconstructed Matrix A (Q @ R):")
print(A_reconstructed)

Matrix A:
[[ 2 -2 18]
 [ 2  1  0]
 [ 1  2  0]]

Matrix Q (Orthogonal Matrix):
[[-0.66666667  0.66666667  0.33333333]
 [-0.66666667 -0.33333333 -0.66666667]
 [-0.33333333 -0.66666667  0.66666667]]

Matrix R (Upper Triangular Matrix):
[[-3.0000000e+00  4.4408921e-16 -1.2000000e+01]
 [ 0.0000000e+00 -3.0000000e+00  1.2000000e+01]
 [ 0.0000000e+00  0.0000000e+00  6.0000000e+00]]

Reconstructed Matrix A (Q @ R):
[[ 2.00000000e+00 -2.00000000e+00  1.80000000e+01]
 [ 2.00000000e+00  1.00000000e+00  2.22044605e-16]
 [ 1.00000000e+00  2.00000000e+00  2.22044605e-16]]


#**1.3.2 Least-squares problems**

#####Least squares problems are problems where the goal is to find the best-fit solution to an overdetermined system of linear equations (i.e., there are more equations than unknowns). The idea is to minimize the sum of the squared differences between the observed data points and the model's predicted values. Given $A \in \mathbb{R}^{m x n}$ and $\textbf{b} \in \mathbb{R}^m$. The least squares approach looks for $\textbf{x}$ that minimizes the residual sum of squares: $$\underset{x}{min}\:||A\textbf{x}-\textbf{b}||^2$$

In [2]:
import numpy as np

# Sample data points (x, y)
x = np.array([0, 1, 2, 3, 4])
y = np.array([1, 3, 2, 5, 7])

# Construct the design matrix A (add a column of ones for the intercept)
A = np.vstack([x, np.ones(len(x))]).T

# Solve the least squares problem: find m (slope) and c (intercept) such that y = mx + c
m, c = np.linalg.lstsq(A, y, rcond=None)[0]

# Print the slope and intercept
print(f"Slope (m): {m}")
print(f"Intercept (c): {c}")

# Generate the line of best fit
line = m * x + c

# Output the fitted line values
print("\nFitted line values:")
print(line)

Slope (m): 1.4
Intercept (c): 0.7999999999999989

Fitted line values:
[0.8 2.2 3.6 5.  6.4]


#**1.3.3 Linear Regression**

#####Linear regression is used to model the linear relationship between a dependent variable $y$ and one or more independent variables $x_1, x_2,...., x_n$. The goal is to find the best-fitting line or hyperplane that predicts $y$ based on the input variables. The formula for simple linear regression with one independent variable is $y=mx+c$, where $m$ is the slope and $c$ is the intercept.

In [3]:
import numpy as np
from sklearn.linear_model import LinearRegression

# Sample data: x represents the independent variable and y the dependent variable
x = np.array([1, 2, 3, 4, 5]).reshape(-1, 1)  # Reshape because scikit-learn expects 2D input
y = np.array([1, 4, 9, 16, 25])  # This is a quadratic relationship, but we'll fit a linear model for simplicity

# Create a linear regression model
model = LinearRegression()

# Fit the model to the data
model.fit(x, y)

# Print the slope (m) and intercept (c)
print(f"Slope (m): {model.coef_[0]}")
print(f"Intercept (c): {model.intercept_}")

# Predict values based on the model
predicted_y = model.predict(x)

# Output the predicted values
print("\nPredicted values:")
print(predicted_y)


Slope (m): 5.999999999999999
Intercept (c): -6.9999999999999964

Predicted values:
[-1.  5. 11. 17. 23.]
